services:
  caddy:
    profiles:
      - edge

  pds:
    environment:
      - PORT=3000
      - PDS_PORT=3000
      - PDS_HOSTNAME=localhost
    ports:
      - "3000:3000"

  plc:
    ports:
      - "4000:4000"

  relay_db:
    ports:
      - "5432:5432"

  relay:
    network_mode: host
    environment:
      - DATABASE_URL=postgres://relaypg:${RELAY_POSTGRES_PASSWORD}@localhost:5432/relay
      - RELAY_API_LISTEN=:2470
      - RELAY_PLC_HOST=http://localhost:4000

  jetstream:
    network_mode: host
    environment:
      - JETSTREAM_RELAY_URL=http://localhost:2470
      - JETSTREAM_PLC_URL=http://localhost:4000
